---
title: "GISRUK 2026 : University of Birmingham"
---

::: {.callout-important icon=true}


### Updates

**Welcome**. We very much look forward to seeing you in Birmingham! Keep an eye out on this page as we post further updates in in the run up to and during the conference. 



---------

Welcome to the 34th Annual GIS Research UK Conference. The conference will be hosted at the University of Birmingham, 15th – 17th April 2026, with an early career session on the 14th April.

GISRUK hosts research from across geographic information science, from fundamental research to applications of GIScience across many domains. This year, the theme is People, Planet, and Progress: GIS for Real-World Impact, and we are particularly excited to invite submissions that describe practical applications of GIS that align to the UN Sustainable Development Goals, from both academia and practice. Beyond this special invitation, we accept abstracts in the following topics, and beyond.

## GISRUK 2026 best paper awards open vote!

There will be an open vote throughout the conference for the best papers! There are three awards, one for each of the following categories:
- Best poster presentation
- Best paper, student registration (oral presentation)
- Best paper, standard registration (oral presentation)

To cast your votes, please complete the following form [here](https://forms.office.com/e/Qqj95c12YM)

We will announce the winners at the conference closing session on Friday 17th April. Thanks in advance for your input!

## Key Dates

* Call for papers: ~~30 January 2026~~  
* Registration deadline: ~~23 March 2026~~
* Conference: 14-17 April 2026

For more information on GISRUK, please visit: [https://gisruk.org/](https://gisruk.org/)
