---
title: "Accommodation"
---

There is limited accommodation near the University of Birmingham Edgbaston campus, therefore it is recommended to book accommodation within Birmingham city centre. The campus is located approximately 10 minutes by train (via West Midlands Railway) from Birmingham New Street. The station located on campus is called “University”.

## Accommodation on the University of Birmingham Campus:

Please note, there is limited availability for the following: 

- [Edgbaston Park Hotel](https://www.edgbastonparkhotel.com)
- [Peter Scott House](https://www.edgbastonparkhotel.com/rooms/peter-scott-house)

## Accommodation options in Birmingham City Centre:

- [Macdonald Burlington Hotel](https://www.macdonaldhotels.co.uk/burlington)
- [Radisson Blu Hotel, Birmingham](https://www.radissonhotels.com/en-us/hotels/radisson-blu-birmingham)
- [Aparthotel Adagio Birmingham City Centre](https://www.adagio-city.com/gb/hotel-8117-aparthotel-adagio-birmingham-city-centre/index.shtml)
- [Britannia Hotel Birmingham New Street Station](https://www.britanniahotels.com/hotels/the-britannia-hotel-birmingham)
- [Holiday Inn Birmingham City](https://www.ihg.com/holidayinn/hotels/gb/en/birmingham/bhxwm/hoteldetail)
- [Premier Inn Birmingham City Centre (Exchange Square)](https://www.premierinn.com/gb/en/hotels/england/west-midlands/birmingham/birmingham-city-centre-exchange-square.html)
- [Premier Inn Birmingham City Centre (New Street Station)](https://www.premierinn.com/gb/en/hotels/england/west-midlands/birmingham/birmingham-city-centre-new-st-station.html)
- [Premier Inn Birmingham City Centre (Waterloo Street)](https://www.premierinn.com/gb/en/hotels/england/west-midlands/birmingham/birmingham-city-centre-waterloo-street.html)
- [easyHotel Birmingham City Centre](https://www.easyhotel.com/hotels/united-kingdom/birmingham/birmingham-city-centre)
- [Travelodge Birmingham Central Moor Street](https://www.travelodge.co.uk/hotels/531/Birmingham-Central-Moor-Street-hotel)
- [Travelodge Birmingham Central Bull Ring](https://www.travelodge.co.uk/hotels/503/Birmingham-Central-Bull-Ring-hotel)
- [Travelodge Birmingham Central](https://www.travelodge.co.uk/hotels/109/Birmingham-Central-hotel)
- [Comfort Inn Birmingham](https://www.choicehotels.com/en-uk/united-kingdom/birmingham/comfort-inn-hotels/gb655)
