---
title: "The GISRUK Conference Proceedings"
subtitle: "About the proceedings"
---

** GISRUK uses [Zenodo](https://zenodo.org) to host the annual GISRUK conference proceedings**. Zenodo provides an open access repository to host the proceedings and offers long term availability of these resources. Every GISRUK paper/abstract uploaded to Zenodo is given a unique DOI which allows for wider dissemination and citation of these works. 

The proceedings for GISRUK 2026 are available on [Zenodo](https://zenodo.org/communities/gisruk2026/records?q=&l=list&p=1&s=100&sort=newest) - from here you can access the PDF versions of all of the accepted papers for GISRUK 2026. Each proceedings entry has its own DOI. When sharing the link to any of the proceedings entries please used the DOI. You can use the previous link to share the general link to the full set of proceedings. 

## Preparing your abstract paper for the Zenodo proceedings

There are a number of important steps to consider before your paper can be uploaded to Zenodo for the GISRUK 2026 proceedings. A simple checklist to prepare your document for the proceedings is provided below. Failure to follow the steps below may result in your paper not being included in the GISRUK 2026 proceedings. 

- [ ] The final abstract document is a PDF document prepared using the GISRUK Template ([Word](https://gisruk.github.io/files/GISRUK2025_PaperTemplateSubmission.docx), [LaTeX](https://gisruk.github.io/files/GISRUK2025_PaperTemplateSubmission.zip), [Quarto](https://github.com/sdesabbata/quarto-gisruk)). 
- [ ] No additional changes, modifications, edits, or typesetting adjustments are needed to the final abstract PDF. 
- [ ] You have integrated the feedback provided by the reviewers as far as you are able. In particular, you are asked to take action where the reviewers have indicated issues around the formatting or presentation of the paper. 
- [ ] The figures, text, and tables in the final abstract PDF are typeset as you intend them to be read. Generally, tables/figures are placed in-line, rather than at the end.
- [ ] The text is free of typographical errors, and has been thoroughly proofread. 
- [ ] Each citation in the text has a corresponding reference in the bibliography.
- [ ] Each reference in the bibliography has at least one citation within the text. 
- [ ] The affiliations and contact details for *all of the authors* are correct at the time of submission. This includes the institutional names, addresses, etc.
- [ ] Each author on the submission has a corresponding biography at the end of the paper. 
- [ ] The submitting author, or a designated attending author, has registered for the conference. If the lead author is not registered, then the "presenting author" is indicated in the author information. 
- [ ] Do not create a Zenodo resource yourself - this will be performed by the GISRUK proceedings committee. 

Once your abstract satisfies all of the above conditions, please email it to the conference organisers using the email address that you recieved when your abstract was accepted. The subject of the email should have `GISRUK-Proceedings-` and your abstract number (like, `GISRUK-Proceedings-121`). 

** Your final camera ready abstract for the proceedings must be submitted to the conference organisers as outlined in the communications via email after abstract acceptance.**

We respectfully reserve the right to exclude your paper from the GISRUK Proceedings unless it meets these guidance notes to the satisfaction of the GISRUK Proceedings coordinator(s). It is __very important__ to ensure that the *final PDF provided to us is ready to publish __as is__*. Each item in the GISRUK Proceedings requires us to manually generate a Digital Object Identifier (DOI). Any changes after a DOI is created must be carried out by the Zenodo team based on our request.  

## Recent GISRUK Proceedings on Zenodo 

The previous five GISRUK conferences have their proceedings available on Zenodo. The links to each conference is provided below. 

* 2025 Bristol Proceedings [GISRUK 2025 Proceedings](https://zenodo.org/communities/gisruk2025) 
* 2024 Leeds Proceedings [GISRUK 2024 Proceedings](https://zenodo.org/communities/gisruk2024)
* 2023 Glasgow Proceedings [GISRUK 2023 Proceedings](https://zenodo.org/communities/gisruk2023)
* 2022 Liverpool Proceedings [GISRUK 2022 Proceedings](https://zenodo.org/communities/gisruk2022) 
* 2021 Cardiff Proceedings [GISRUK 2021 Proceedings](https://zenodo.org/communities/gisruk_2021)


